### PR TITLE
Fix 5064 provide ability to copy crash information

### PR DESCRIPTION
**Pull request by RussKie**
Relates to gitextensions/gitextensions#5064

## Proposed changes

* Remove "Send and quit" button
* Add "Copy" button to copy full exception information
* Add copy exception information in MD format

A copied information looks similar to the following:

````
## Current behaviour

```
System.DivideByZeroException: Boom!
   at GitUI.CommitInfo.CommitInfo.ReloadCommitInfo() in C:\Development\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 241
   at GitUI.CommitInfo.CommitInfo.SetRevisionWithChildren(GitRevision revision, IReadOnlyList`1 children) in C:\Development\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 200
   at GitUI.CommandsDialogs.FormBrowse.FillCommitInfo() in C:\Development\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1247
   at GitUI.CommandsDialogs.FormBrowse.<.ctor>b__53_2(Object sender, EventArgs e) in C:\Development\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 204
   at GitUI.RevisionGridControl.<.ctor>b__108_0(Object _, EventArgs e) in C:\Development\gitextensions\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 159
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information

A problem occurred while I was arguing with someone on the internet :)

## Environment

- Git Extensions 3.1.0
- Build 259c501a27db6de9723fbcddbdd40638a9498f24 (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 144dpi (150% scaling)
````

### Before

crash screen

### After

image

## Test methodology 

- manual, added an exception to `CommitInfo` control and observed it handled by the NBug.

## Test environment(s) 

- Git Extensions 3.1.0
- Build 259c501a27db6de9723fbcddbdd40638a9498f24 (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 144dpi (150% scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
I get no information in _Environment_

image

**Comment by RussKie** [comment]
> I get no information in _Environment_

I'd be surprised if you did 😄 
It requires an additional hook on the GE side
```diff
diff --git a/GitExtensions/Program.cs b/GitExtensions/Program.cs
index 8374b2e6a..52c2ff918 100644
--- a/GitExtensions/Program.cs
+++ b/GitExtensions/Program.cs
@@ -40,8 +40,15 @@ private static void Main()
                 NBug.Settings.StopReportingAfter = 90;
                 NBug.Settings.SleepBeforeSend = 30;
                 NBug.Settings.StoragePath = NBug.Enums.StoragePath.WindowsTemp;
+                NBug.Settings.GetSystemInfo = () =>
+                {
+                    // if the error happens before we had a chance to init the environment information
+                    // the call to GetInformation() will fail. A double Initialise() call is safe.
+                    UserEnvironmentInformation.Initialise(ThisAssembly.Git.Sha, ThisAssembly.Git.IsDirty);
+                    return UserEnvironmentInformation.GetInformation();
+                };
```

Thank you for the screenshot, all strings are localised so changing this text would be a pain 😕 
I'm currently building a GH integration, and hopefully it won't be too difficult. Then we won't need to change the text.

However you screenshot made me realise I completely forgotten about the user comments textbox, I'll fix it up.

**Comment by RussKie** [comment]
Additional info is now copied as well.

**Comment by RussKie** [comment]
@gerhardol any objections?

**Pull request merged**
